version: "3"
services:

    mysql:
        image: ${MYSQL_IMAGE_NAME}
        volumes:
            - ./my.cnf:/etc/my.cnf
            - ./conf:/etc/mysql/conf.d
            - ./data:/var/lib/mysql

        restart: always
        privileged: true
        container_name: ${MYSQL_CONTAINER_NAME}
        environment:
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

        ports:
            - "3306:3306"
        networks:
            - database_app

    redis:
        image: ${REDIS_IMAGE_NAME}
        restart: always
        container_name: ${REDIS_CONTAINER_NAME}
        ports:
            - "6379:6379"
        networks:
            - database_app

    phpmyadmin:
        image: ${MYADMIN_IMAGE_NAME}
        restart: always
        environment:
            - UPLOAD_LIMIT=${MYADMIN_UPLOAD_LIMIT}
            - PMA_HOST=${MYSQL_CONTAINER_NAME}
            - PMA_PORT=3306
            - PMA_USER=root
            - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
        ports:
            - 8888:80
        networks:
            - database_app
            
networks: 
    database_app:
        external: true